comida = input("comida favorita = ")
print("su comida favorita es = ", comida)
print("su comida tiene ", len(comida), "caracteres")
print("la primera letra de su comida es = ", comida[0] )
print("la ultima letra de su comida es = ", comida[-1])
print("su comida contiene la lera a ", "a" in comida)
print("su comida contiene la letra e ", "e" in comida)
print(comida[2])
print(comida[-2])